### ISSUE TITLE
Highlighting for RWS

### ISSUE THREAD

**Issue by Rahler** [nyanlathotep/royal-advisory-board#1]
Could you add some sort of highlighting to RWS? I've been using it for a LF build, so I've just been replacing the ulJoin function with 

```javascript
function ulJoin (a){
    list="<ol>"
    for(i=0;i<a.length;i++) {
        if(a[i].match(/Blacksmith/))
            list+='<li style="color:blue">'
        else
            list+="<li>"
        list+=a[i]+"</li>"
    }
    list+="</ol>"
    return list
}
```
But something more general (maybe with a radio selector to pick what to highlight) would probably be better for the site.

**Comment by nyanlathotep** [comment]
Yeah, this has been requested before. I'll look into this when I revamp RWS, along with being able to test alternate sets of buildings and get your forecast even when not neutral. Thanks for the suggestion!

**Comment by nyanlathotep** [comment]
This has been added to general youri's fork.
