### ISSUE TITLE
Saves no longer work in v1.5.42.5

### ISSUE THREAD

**Issue by Nessworthy** [nyanlathotep/royal-advisory-board#2]
See title, exported saves produce invalid save messages for the weather forecast.

**Comment by nyanlathotep** [comment]
Yep, 1.5 changed the save format. What I've seen of it is as stupid as I've come to expect from DivineGames. That coupled with the sleazy bullshit they did with rubies has pretty much killed my interest in RG, so it's not likely I'm going to work on this. I will, however, review pull requests if I get any.
